# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listDish = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listDish.sizePolicy().hasHeightForWidth())
        self.listDish.setSizePolicy(sizePolicy)
        self.listDish.setObjectName("listDish")
        self.horizontalLayout_2.addWidget(self.listDish)
        self.listQuanti = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listQuanti.sizePolicy().hasHeightForWidth())
        self.listQuanti.setSizePolicy(sizePolicy)
        self.listQuanti.setObjectName("listQuanti")
        self.horizontalLayout_2.addWidget(self.listQuanti)
        self.listPrice = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listPrice.sizePolicy().hasHeightForWidth())
        self.listPrice.setSizePolicy(sizePolicy)
        self.listPrice.setObjectName("listPrice")
        self.horizontalLayout_2.addWidget(self.listPrice)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 7, 3, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 7, 2, 1, 1)
        self.display = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 6, 2, 1, 3)
        self.btnOk = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout.addWidget(self.btnOk, 10, 4, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 8, 2, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 7, 4, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 10, 3, 1, 1)
        self.btnQuanti = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnQuanti.setObjectName("btnQuanti")
        self.gridLayout.addWidget(self.btnQuanti, 10, 2, 1, 1)
        self.btnOrder = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnOrder.setObjectName("btnOrder")
        self.gridLayout.addWidget(self.btnOrder, 11, 3, 1, 2)
        self.labelTable = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTable.setFont(font)
        self.labelTable.setText("")
        self.labelTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTable.setObjectName("labelTable")
        self.gridLayout.addWidget(self.labelTable, 0, 2, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 12, 3, 1, 1)
        self.btnDel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnDel.setObjectName("btnDel")
        self.gridLayout.addWidget(self.btnDel, 11, 2, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 9, 3, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 9, 4, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 8, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 8, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 3)
        self.totalPrice = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalPrice.sizePolicy().hasHeightForWidth())
        self.totalPrice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.totalPrice.setFont(font)
        self.totalPrice.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.totalPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalPrice.setObjectName("totalPrice")
        self.gridLayout.addWidget(self.totalPrice, 6, 1, 1, 1)
        self.labelDish = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDish.setFont(font)
        self.labelDish.setText("")
        self.labelDish.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDish.setObjectName("labelDish")
        self.gridLayout.addWidget(self.labelDish, 4, 2, 1, 3)
        self.btn7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 9, 2, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 100))
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 12, 4, 1, 1)
        self.btnMinus = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnMinus.setObjectName("btnMinus")
        self.gridLayout.addWidget(self.btnMinus, 11, 1, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 9, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 7, 1, 1, 1)
        self.btnPay = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnPay.setObjectName("btnPay")
        self.gridLayout.addWidget(self.btnPay, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label.setText(_translate("MainWindow", "Quanti"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.display.setText(_translate("MainWindow", "0"))
        self.btnOk.setText(_translate("MainWindow", "OK"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnQuanti.setText(_translate("MainWindow", "*"))
        self.btnOrder.setText(_translate("MainWindow", "Order"))
        self.btnDel.setText(_translate("MainWindow", "<-"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.label_4.setText(_translate("MainWindow", "Pick Dish"))
        self.totalPrice.setText(_translate("MainWindow", "0"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.btnMinus.setText(_translate("MainWindow", "-1"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))
        self.btnPay.setText(_translate("MainWindow", "Pay"))

